name: GitHub Actions test
run-name: HW for SS, task 2
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ls -Al
      - run: pip install -r requirements.txt
      - run: coverage run -m pytest
      - run: coverage report -m | grep TOTAL | sed 's/^.* \([0-9]\+\)%.*$/\1/'
