name: GitHub Actions test
run-name: HW for SS, task 2
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip install -r requirements.txt
      - run: |
          echo $(coverage run -m pytest --cov-report=term --cov=.
          grep TOTAL |
          sed 's/^.* \([0-9]\+\)%.*$/\1/')
